name: "Build and Publish Docker Image"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check_update:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.check_base_image.outputs.needs-updating }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if Base Image Updated
        id: check_base_image
        if: github.event_name == 'schedule'
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: "node:slim"
          image: "realies/tgmr:latest"
        continue-on-error: true

      - name: Set needs_update for non-schedule events
        if: github.event_name != 'schedule'
        run: echo "needs-updating=true" >> $GITHUB_OUTPUT
        id: force_update

  build:
    needs: check_update
    runs-on: ubuntu-latest
    if: needs.check_update.outputs.needs_update == 'true' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: realies/tgmr
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64 
